name: My First GitHub Actions

on: [push]
jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Say Hello
          run: echo "Hello, GitHub Actions!"

        - name: Setup Java JDK
          uses: actions/setup-java@v5.0.0
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'
        - name: Build with Maven
          run: |
              cd springboot-project
              mvn clean install
  Docker-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.3.0
        with:
          context: ./springboot-project
          file: ./springboot-project/Dockerfile